// todolist/kid react/src/TodoList.jsx
import React, { Component } from "react";
import "./TodoList.css";

class TodoList extends Component {
	constructor() {
		super();
		this.state = { tasks: ["Create app with React", "Make it easy", "Commit on GitHub"] };

		this.addTask = this.addTask.bind(this);
		this.delTask = this.delTask.bind(this);
	}

	addTask(event) {
		event.preventDefault();
		let task = event.target['task'];
		let tasks = this.state.tasks;
		let taskname = task.value;
		if (!taskname) return;
		tasks.push(taskname);
		task.value = "";
		this.setState({ tasks: tasks });
	}

	delTask(event) {
		let taskid = event.target.value;
		let tasks = this.state.tasks;
		tasks.splice(taskid, 1);
		this.setState({ tasks: tasks });
	}

	render() {
		return(
			<div>
				<ul>
					{ this.state.tasks.map((task, id) => (
						<li key={id}>
							{ task }
							<button onClick={this.delTask} value={id}>&times;</button>
						</li>
					)) }
				</ul>

				<form onSubmit={this.addTask}>
					<input type="text" name="task" placeholder="Other task..." autoFocus />
					<input type="submit" value="Add task" />
				</form>
			</div>
		);
	}
}

export default TodoList;

// todolist/svelte power/src/TodoList.svelte
<script>
	let tasks = ["Create app with Svelte", "It's more easily than React"];

	function addTask(event) {
		event.preventDefault();
		let task = event.target['task'];
		let taskname = task.value;
		if (!taskname) return;
		tasks = [...tasks, taskname]
		task.value = "";
	}

	function delTask(event) {
		let taskid = event.target.value;
		tasks = tasks.filter((task, id) => id != taskid);
	}
</script>

<style>
	button {
		visibility: hidden;
		color: red;
		border: none;
		background-color: transparent;
		font-weight: bold;
	}

	li:hover button {
		visibility: visible;
		cursor: pointer;
	}
</style>

<ul>
	{#each tasks as task, id}
		<li>
			{task}
			<button on:click={delTask} value={id}>&times;</button>
		</li>
	{/each}
</ul>

<form on:submit={addTask}>
	<input type="text" name="task" placeholder="Other task..." />
	<input type="submit" value="Add task" />
</form>
